spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fleet_db?createDatabaseIfNotExist=true
    username: service
    password: service
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

server:
  port: 8092
B